# Generated by Django 3.1.2 on 2020-10-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201006_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='The text to display in the comment', max_length=500),
        ),
    ]
