# Generated by Django 3.1.2 on 2020-10-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201006_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['posted']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted'], 'permissions': (('can_post', 'Can author blog posts'),)},
        ),
    ]
